Repository dfinity/portal, pull requests merged in 2022-07, with the labels that each got.

#240 Update and fix the reproducible builds docs.
  docs/developer-docs/build/backend/reproducible-builds.md
Labels: cla:agreed

#324 Fix the dead link to Reproducible canisters
  docs/concepts/trust-in-canisters.md
Labels: cla:pending, cla:agreed

#335 Add environment variables to build IC script
  .github/workflows/cd.yml
Labels: kind:bug
