Repository dfinity/portal, pull requests merged in 2023-10, with the labels that each got.

#1956 Safenote project added to showcase.
  showcase.json
  static/img/showcase/safenote_logo.webp
  static/img/showcase/safenote_screenshot.webp
Labels: external-contributor

#1968 Add John Dao to showcase
  showcase.json
  static/img/showcase/john-dao_logo.webp
  static/img/showcase/john-dao_screenshot.webp
Labels: external-contributor

#1892 Add/pos docs
  docs/samples/overview.md
  docs/samples/pos.md
  sidebars.js
Labels: cla:agreed, external-contributor

#1977 Add ICP.NET candid implementation
  docs/developer-docs/backend/candid/candid-howto.md
Labels: external-contributor

#1821 Update Vibeverse showcase
  showcase.json
  static/img/showcase/vibeverse_logo.png
  static/img/showcase/vibeverse_screenshot_0.jpg
  static/img/showcase/vibeverse_screenshot_0.png
  static/img/showcase/vibeverse_screenshot_1.jpg
  static/img/showcase/vibeverse_screenshot_1.png
Labels: cla:agreed, external-contributor

#1735 Added "fishverse" to showcase
  showcase.json
  static/img/showcase/fishverse_logo.webp
  static/img/showcase/fishverse_screenshot.webp
Labels: cla:agreed

#1979 aVa Verification showcase
  showcase.json
  static/img/showcase/ava_logo.webp
  static/img/showcase/ava_screenshot.webp
Labels: cla:agreed, external-contributor

#1950 Add 221Bravo App to portal showcase
  showcase.json
  static/img/showcase/bravo-app_logo.webp.webp
  static/img/showcase/bravo-app_screenshot.webp.webp
Labels: cla:agreed, external-contributor

#1987 fix typo in image name
  static/img/showcase/bravo-app_logo.webp
  static/img/showcase/bravo-app_screenshot.webp
Labels: external-contributor

#1725 Tswaanda showcasing pull request
  showcase.json
  static/img/showcase/tswaanda_logo.jpg
  static/img/showcase/tswaanda_screenshot_0.png
  static/img/showcase/tswaanda_screenshot_1.png
  static/img/showcase/tswaanda_video.mp4
Labels: external-contributor

#1992 chore(docs): dfx deploy must be run in project dir
  docs/developer-docs/setup/quickstart.md
Labels: cla:agreed, external-contributor

#1990 Fix motoko-tutorial URL
  docs/motoko/tutorial.mdx
Labels: external-contributor

#1980 Update showcase.json
  showcase.json
Labels: external-contributor

#2007 Add dFlow project to showcase
  showcase.json
  static/img/showcase/dflow_logo.png
  static/img/showcase/dflow_screenshot.png
Labels: external-contributor

#2014 Update showcase.json
  showcase.json
Labels: cla:agreed, external-contributor

#2016 DooCoins images for showcase
  static/img/showcase/doocoins_logo.webp
  static/img/showcase/doocoins_screenshot.webp
Labels: cla:agreed, external-contributor

#2008 Update showcase.json
  showcase.json
Labels: external-contributor

#2034 Cubetopia showcase update
  showcase.json
  static/img/showcase/cubetopia_screenshot.webp
Labels: cla:agreed, external-contributor

#2037 add ccamp to showcase
  showcase.json
  static/img/showcase/ccamp_logo.webp
  static/img/showcase/ccamp_screenshot.webp
Labels: external-contributor

#1513 Update showcase.json from Faceless project
  showcase.json
Labels: cla:agreed, external-contributor

#1985 Add sama network with icp showcase
  showcase.json
  static/img/showcase/sama_network_logo.png
Labels: external-contributor

#2035 Added BTC Flower to Showcase.
  showcase.json
  static/img/showcase/fpdao_logo.png
  static/img/showcase/fpdao_screenshot.png
Labels: cla:agreed, external-contributor
