Repository dfinity/portal, pull requests merged in 2023-08, with the labels that each got.

#1763 add ruby ic agent
  docs/developer-docs/agents/index.md
Labels: cla:agreed

#1767 Add showcase: ICHUB
  showcase.json
  static/img/showcase/ichub_logo.png
  static/img/showcase/ichub_screenshot_0.jpeg
  static/img/showcase/ichub_screenshot_1.jpeg
  static/img/showcase/ichub_screenshot_2.jpeg
Labels: cla:agreed

#1769 W3NS grant submission
  showcase.json
  static/img/w3ns_logo.png
Labels: cla:agreed

#1778 changed array to string for logo field
  showcase.json
Labels: external-contributor

#1780 hashkeydid pr
  showcase.json
  static/img/showcase/hashkeydid_logo.svg
Labels: cla:agreed, external-contributor

#1789 chore: fix typo
  blog/features/vetkey-primer.md
Labels: external-contributor

#1795 updated website link
  showcase.json
Labels: external-contributor

#1796 Add cycleops and simple docs
  docs/developer-docs/setup/cycles/cycles_management_services.md
  showcase.json
  sidebars.js
  static/img/showcase/cycleops_logo.png
Labels: cla:agreed, external-contributor

#1686 add showcase: Chainsight
  showcase.json
  static/img/showcase/chainsight_logo.webp
  static/img/showcase/chainsight_screenshot.webp
Labels: cla:pending

#1820 Fix typo
  docs/developer-docs/setup/cycles/index.md
Labels: external-contributor

#1819 Add MotokoPilot to showcase
  showcase.json
  src/components/Common/toolingItems.ts
  static/img/showcase/motokopilot_logo.png
  static/img/showcase/motokopilot_screenshot.jpg
Labels: external-contributor

#1825 Add Ethereum canister to the showcase
  showcase.json
Labels: cla:agreed, external-contributor

#1839 showcase: add cyql.io
  showcase.json
  static/img/showcase/cyqlio_logo.svg
  static/img/showcase/cyqlio_screenshot.webp
Labels: external-contributor

#1851 Edit orders and tags on showcase.json
  showcase.json
Labels: external-contributor

#1852 Add zondax unreal to showcase
  showcase.json
  static/img/showcase/zondax-unreal_logo.webp
  static/img/showcase/zondax-unreal_screenshot_0.webp
Labels: external-contributor

#1847 Update exchange-rate-canister.md
  docs/developer-docs/integrations/exchange-rate/exchange-rate-canister.md
Labels: external-contributor

#1858 W3NS submission - Fixed logo path
  static/img/showcase/w3ns_logo.png
Labels: external-contributor

#1859 Added pluto showcase
  showcase.json
Labels: external-contributor

#1606 motoko-book
  showcase.json
  static/img/showcase/motoko-book_logo.png
Labels: cla:agreed, external-contributor
