Repository dfinity/portal, pull requests merged in 2024-11, with the labels that each got.

#3690 Update indexes.mdx
  docs/developer-docs/defi/tokens/indexes.mdx
Labels: external-contributor

#3658 Dragginz II custom page
  showcase.json
  static/img/showcase/dragginz_logo.png
  static/img/showcase/dragginz_logo.svg
Labels: external-contributor

#3714 kongswap showcase
  showcase.json
Labels: external-contributor

#3755 [FINAL] feat: Add sections for new subnet_info endpoint
  docs/references/_attachments/ic.did
  docs/references/_attachments/interface-spec-changelog.md
  docs/references/ic-interface-spec.md
Labels: interface-spec

#3762 [FINAL] feat: 64-bit system API
  docs/references/_attachments/interface-spec-changelog.md
  docs/references/ic-interface-spec.md
Labels: interface-spec

#3784 chore: tag PR with interface-spec
  .github/workflows/interface-spec.yml
Labels: interface-spec

#3778 Docs audit 1
  docs/developer-docs/developer-tools/ide/gitpod.mdx
  docs/developer-docs/developer-tools/off-chain/agents/nodejs.mdx
  docs/developer-docs/smart-contracts/call/arguments.mdx
  docs/developer-docs/smart-contracts/call/overview.mdx
  docs/developer-docs/smart-contracts/candid/candid-concepts.mdx
  docs/developer-docs/smart-contracts/candid/candid-howto.mdx
  docs/developer-docs/smart-contracts/candid/index.mdx
  docs/developer-docs/smart-contracts/compile.mdx
  docs/developer-docs/smart-contracts/create.mdx
  docs/developer-docs/smart-contracts/deploy/custom-testnets.mdx
  docs/developer-docs/smart-contracts/deploy/overview.mdx
  docs/developer-docs/smart-contracts/development-workflow.mdx
  docs/developer-docs/smart-contracts/install.mdx
  docs/developer-docs/smart-contracts/overview/canister-lifecycle.mdx
  docs/developer-docs/smart-contracts/overview/trust-in-canisters.mdx
  docs/developer-docs/smart-contracts/write/auto-scaling-architecture.mdx
  docs/developer-docs/smart-contracts/write/default-template.mdx
  docs/developer-docs/smart-contracts/write/overview.mdx
  docs/developer-docs/smart-contracts/write/resources.mdx
  docs/tutorials/hackathon-prep-course/10-resources.mdx
  plugins/utils/redirects.js
  sidebars.js
Labels: documentation

#3810 fix: GlossaryTooltip
  docs/developer-docs/smart-contracts/compile.mdx
Labels: documentation
