Repository dfinity/portal, pull requests merged in 2024-12, with the labels that each got.

#3828 update: List of supported wallets
  docs/developer-docs/defi/wallets/overview.mdx
Labels: documentation

#3830 add: disabled Testnet BTC API warning
  docs/developer-docs/multi-chain/bitcoin/using-btc/btc-dev-workflow.mdx
  docs/developer-docs/multi-chain/bitcoin/using-btc/local-development.mdx
  docs/developer-docs/multi-chain/bitcoin/using-btc/submit-transactions.mdx
Labels: documentation

#3824 fix: clarify stable memory
  docs/developer-docs/smart-contracts/maintain/storage.mdx
Labels: documentation

#3809 Docs audit #3
  docs/developer-docs/getting-started/install.mdx
  docs/developer-docs/getting-started/troubleshooting.mdx
  docs/developer-docs/smart-contracts/advanced-features/async-code.mdx
  docs/developer-docs/smart-contracts/advanced-features/composite-query.mdx
  docs/developer-docs/smart-contracts/advanced-features/handling-get-post-requests.mdx
  docs/developer-docs/smart-contracts/advanced-features/http-gateways.mdx
  docs/developer-docs/smart-contracts/advanced-features/https-outcalls/https-outcalls-get.mdx
  docs/developer-docs/smart-contracts/advanced-features/https-outcalls/https-outcalls-how-to-use.mdx
  docs/developer-docs/smart-contracts/advanced-features/https-outcalls/https-outcalls-post.mdx
  docs/developer-docs/smart-contracts/advanced-features/serving-http-request.mdx
  docs/developer-docs/smart-contracts/test/overview.mdx
  docs/developer-docs/smart-contracts/test/pocket-ic.mdx
  docs/developer-docs/smart-contracts/test/staging-environment.mdx
  docs/developer-docs/smart-contracts/test/troubleshooting.mdx
  docs/developer-docs/smart-contracts/topping-up/cycles_management_services.mdx
  docs/developer-docs/smart-contracts/topping-up/topping-up-canister.mdx
  docs/other/updates/release-notes/sdk-release-notes.md
  docusaurus.config.js
  plugins/utils/redirects.js
  sidebars.js
Labels: documentation

#3801 Docs Audit #2
  docs/developer-docs/getting-started/install.mdx
  docs/developer-docs/getting-started/troubleshooting.mdx
  docs/developer-docs/smart-contracts/advanced-features/async-code.mdx
  docs/developer-docs/smart-contracts/advanced-features/composite-query.mdx
  docs/developer-docs/smart-contracts/advanced-features/handling-get-post-requests.mdx
  docs/developer-docs/smart-contracts/advanced-features/http-gateways.mdx
  docs/developer-docs/smart-contracts/advanced-features/https-outcalls/https-outcalls-get.mdx
  docs/developer-docs/smart-contracts/advanced-features/https-outcalls/https-outcalls-how-to-use.mdx
  docs/developer-docs/smart-contracts/advanced-features/https-outcalls/https-outcalls-post.mdx
  docs/developer-docs/smart-contracts/advanced-features/serving-http-request.mdx
  docs/developer-docs/smart-contracts/maintain/control.mdx
  docs/developer-docs/smart-contracts/maintain/delete.mdx
  docs/developer-docs/smart-contracts/maintain/history.mdx
  docs/developer-docs/smart-contracts/maintain/import.mdx
  docs/developer-docs/smart-contracts/maintain/logs.mdx
  docs/developer-docs/smart-contracts/maintain/recovery.mdx
  docs/developer-docs/smart-contracts/maintain/settings.mdx
  docs/developer-docs/smart-contracts/maintain/snapshots.mdx
  docs/developer-docs/smart-contracts/maintain/state.mdx
  docs/developer-docs/smart-contracts/maintain/storage.mdx
  docs/developer-docs/smart-contracts/maintain/trapping.mdx
  docs/developer-docs/smart-contracts/maintain/upgrade.mdx
  docs/developer-docs/smart-contracts/test/overview.mdx
  docs/developer-docs/smart-contracts/test/pocket-ic.mdx
  docs/developer-docs/smart-contracts/test/staging-environment.mdx
  docs/developer-docs/smart-contracts/test/troubleshooting.mdx
  docs/developer-docs/smart-contracts/topping-up/cycles_management_services.mdx
  docs/developer-docs/smart-contracts/topping-up/topping-up-canister.mdx
  docs/other/updates/release-notes/sdk-release-notes.md
  docusaurus.config.js
  plugins/utils/redirects.js
  sidebars.js
Labels: documentation

#3837 fix: page title
  docs/developer-docs/smart-contracts/advanced-features/async-code.mdx
Labels: documentation

#3848 Update icp_ledger_setup.mdx to fix the init args in the example dfx.json file.
  docs/developer-docs/defi/tokens/ledger/setup/icp_ledger_setup.mdx
Labels: documentation

#3847 lint: add link validation plugin
  blog/features/vetkey-primer.md
  blog/news-and-updates/2023-12-06-update.mdx
  blog/news-and-updates/team-spotlight-sdk.mdx
  docs/developer-docs/security/security-best-practices/inter-canister-calls.mdx
  docs/developer-docs/web-apps/custom-domains/dns-setup.mdx
  docs/other/updates/release-notes/0.9.2-rn.md
  docs/references/id-encoding-spec.mdx
  docs/tutorials/developer-journey/level-0/01-ic-overview.mdx
  docs/tutorials/developer-journey/level-0/02-ic-terms.mdx
  docs/tutorials/developer-journey/level-0/03-dev-env.mdx
  docs/tutorials/developer-journey/level-0/04-intro-canisters.mdx
  docs/tutorials/developer-journey/level-0/05-intro-languages.mdx
  docs/tutorials/developer-journey/level-0/06-intro-dfx.mdx
  docs/tutorials/developer-journey/level-1/1.1-live-demo.mdx
  docs/tutorials/developer-journey/level-1/1.2-motoko-lvl1.mdx
  docs/tutorials/developer-journey/level-1/1.3-first-dapp.mdx
  docs/tutorials/developer-journey/level-1/1.4-using-cycles.mdx
  docs/tutorials/developer-journey/level-1/1.5-deploying-canisters.mdx
  docs/tutorials/developer-journey/level-1/1.6-managing-canisters.mdx
  docs/tutorials/developer-journey/level-2/2.1-storage-persistence.mdx
  docs/tutorials/developer-journey/level-2/2.2-advanced-canister-calls.mdx
  docs/tutorials/developer-journey/level-2/2.3-third-party-canisters.mdx
  docs/tutorials/developer-journey/level-2/2.4-intro-candid.mdx
  docs/tutorials/developer-journey/level-2/2.5-unit-testing.mdx
  docs/tutorials/developer-journey/level-2/2.6-motoko-lvl2.mdx
  docs/tutorials/developer-journey/level-3/3.1-package-managers.mdx
  docs/tutorials/developer-journey/level-3/3.2-https-outcalls.mdx
  docs/tutorials/developer-journey/level-3/3.3-certified-data.mdx
  docs/tutorials/developer-journey/level-3/3.4-intro-to-agents.mdx
  docs/tutorials/developer-journey/level-3/3.5-identities-and-auth.mdx
  docs/tutorials/developer-journey/level-3/3.6-motoko-lvl3.mdx
  docs/tutorials/developer-journey/level-4/4.1-icp-ledger.mdx
  docs/tutorials/developer-journey/level-4/4.2-icrc-tokens.mdx
  docs/tutorials/developer-journey/level-4/4.3-ckbtc-and-bitcoin.mdx
  docs/tutorials/developer-journey/level-4/4.4-nns-governance.mdx
  docs/tutorials/developer-journey/level-4/4.5-using-quill.mdx
  docs/tutorials/developer-journey/level-4/4.6-motoko-lvl4.mdx
  docs/tutorials/developer-journey/level-5/5.1-vetKeys-tutorial.mdx
  docs/tutorials/developer-journey/level-5/5.2-ICP-ETH-tutorial.mdx
  docs/tutorials/developer-journey/level-5/5.3-token-swap-tutorial.mdx
  docs/tutorials/developer-journey/level-5/5.4-NFT-tutorial.mdx
  docs/tutorials/developer-journey/level-5/5.5-auction-tutorial.mdx
  docs/tutorials/developer-journey/level-5/5.6-next-steps.mdx
  docusaurus.config.js
  plugins/remark/validate-links.js
Labels: documentation

#3862 chore(ICRC_Ledger): FI-1599: Update ICRC ledger setup docs to point to the new GitHub releases
  docs/developer-docs/defi/tokens/ledger/setup/icrc1_ledger_setup.mdx
Labels: documentation

#3751 Add icptokens.net to showcase
  showcase.json
  static/img/showcase/icptokens_logo.svg
Labels: external-contributor

#3872 fix: Link HTTPS outcalls to the https outcalls overview page
  docs/developer-docs/multi-chain/overview.mdx
Labels: documentation

#3870 fix: WSL install instructions
  docs/developer-docs/getting-started/install.mdx
  docs/developer-docs/getting-started/quickstart/first-smart-contract.mdx
  docs/developer-docs/getting-started/quickstart/react-quickstart.mdx
Labels: documentation

#3869 update: new page headings
  docs/developer-docs/defi/tokens/token-standards.mdx
  docs/developer-docs/getting-started/deploy-and-manage.mdx
  docs/developer-docs/getting-started/deploy/local.mdx
  docs/developer-docs/getting-started/deploy/mainnet.mdx
  docs/developer-docs/getting-started/deploy/testnet.mdx
  docs/developer-docs/getting-started/explore-examples.mdx
  docs/developer-docs/getting-started/identities.mdx
  docs/developer-docs/getting-started/install.mdx
  docs/developer-docs/getting-started/next-steps.mdx
  docs/developer-docs/getting-started/quickstart/first-smart-contract.mdx
  docs/developer-docs/getting-started/quickstart/react-quickstart.mdx
  docs/developer-docs/getting-started/tokens-and-cycles.mdx
  docs/developer-docs/getting-started/troubleshooting.mdx
  docs/developer-docs/getting-started/write-smart-contracts.mdx
  sidebars.js
Labels: documentation

#3873 Developer Weekly Update: Dec 11 2024
  blog/news-and-updates/2024-12-11-update.mdx
  docs/developer-docs/getting-started/deploy-and-manage.mdx
  static/img/blog/dev-update-blog-dec-11.jpg
Labels: documentation

#3877 revise: dfx deps guide
  docs/developer-docs/smart-contracts/maintain/import.mdx
Labels: documentation

#3879 add: ckToken KYT check info
  docs/developer-docs/multi-chain/chain-key-tokens/overview.mdx
Labels: documentation

#3880 fix: update ledger info and docs
  docs/developer-docs/defi/tokens/ledger/setup/icp_ledger_setup.mdx
  docs/developer-docs/defi/tokens/ledger/setup/icrc1_ledger_setup.mdx
  docs/developer-docs/defi/tokens/ledger/usage/icp_ledger_usage.mdx
  docs/developer-docs/defi/tokens/ledger/usage/icrc1_ledger_usage.mdx
Labels: documentation

#3885 Add example for calling an Ethereum smart contract from Motoko
  docs/developer-docs/multi-chain/ethereum/evm-rpc/evm-rpc-canister.mdx
Labels: documentation

#3882 fix: tab formatting
  docs/developer-docs/defi/tokens/ledger/setup/icp_ledger_setup.mdx
  docs/developer-docs/defi/tokens/ledger/setup/icrc1_ledger_setup.mdx
Labels: documentation

#3883 update: asset canister docs
  docs/developer-docs/web-apps/application-frontends/add-stylesheet.mdx
  docs/developer-docs/web-apps/application-frontends/asset-security.mdx
  docs/developer-docs/web-apps/application-frontends/default-frontend.mdx
  docs/developer-docs/web-apps/application-frontends/existing-frontend.mdx
  docs/developer-docs/web-apps/application-frontends/overview.mdx
  docs/developer-docs/web-apps/application-frontends/webpack.mdx
  docs/tutorials/developer-journey/level-1/1.3-first-dapp.mdx
  plugins/utils/redirects.js
  sidebars.js
Labels: documentation

#3884 update: Sidebars and remove all "overview" titles
  README.md
  docs/developer-docs/daos/sns/overview.mdx
  docs/developer-docs/daos/sns/tokenomics/rewards.mdx
  docs/developer-docs/daos/sns/tokenomics/tokenomics-intro.mdx
  docs/developer-docs/defi/dex/overview.mdx
  docs/developer-docs/defi/nfts/overview.mdx
  docs/developer-docs/defi/overview.mdx
  docs/developer-docs/defi/rosetta/icp_rosetta/index.mdx
  docs/developer-docs/defi/rosetta/icrc_rosetta/index.mdx
  docs/developer-docs/defi/token_integrations/index.mdx
  docs/developer-docs/defi/tokens/advanced/direct_integration.mdx
  docs/developer-docs/defi/wallets/overview.mdx
  docs/developer-docs/developer-tools/dev-tools-overview.mdx
  docs/developer-docs/developer-tools/off-chain/agents/overview.mdx
  docs/developer-docs/identity/authentication/overview.mdx
  docs/developer-docs/identity/internet-identity/overview.mdx
  docs/developer-docs/identity/verifiable-credentials/overview.mdx
  docs/developer-docs/multi-chain/bitcoin/overview.mdx
  docs/developer-docs/multi-chain/chain-key-tokens/ckbtc/overview.mdx
  docs/developer-docs/multi-chain/chain-key-tokens/ckerc20/overview.mdx
  docs/developer-docs/multi-chain/chain-key-tokens/cketh/overview.mdx
  docs/developer-docs/multi-chain/chain-key-tokens/overview.mdx
  docs/developer-docs/multi-chain/ethereum/evm-rpc/overview.mdx
  docs/developer-docs/multi-chain/ethereum/overview.mdx
  docs/developer-docs/multi-chain/overview.mdx
  docs/developer-docs/security/security-best-practices/overview.mdx
  docs/developer-docs/smart-contracts/advanced-features/https-outcalls/https-outcalls-overview.mdx
  docs/developer-docs/smart-contracts/call/overview.mdx
  docs/developer-docs/smart-contracts/deploy/overview.mdx
  docs/developer-docs/smart-contracts/encryption/vetkeys.mdx
  docs/developer-docs/smart-contracts/test/overview.mdx
  docs/developer-docs/web-apps/application-frontends/overview.mdx
  docs/references/asset-canister.mdx
  docs/references/bitcoin-how-it-works.mdx
  docs/references/candid-ref.mdx
  docs/references/dashboard/overview.mdx
  docs/references/execution-errors.mdx
  docs/references/https-outcalls-how-it-works.mdx
  docs/references/node-providers/overview.mdx
  sidebars.js
  style-guide.md
Labels: documentation

#3902 fix: page title
  docs/developer-docs/smart-contracts/overview/introduction.mdx
  sidebars.js
Labels: documentation

#3896 fix: page title
  docs/developer-docs/web-apps/application-frontends/overview.mdx
Labels: documentation

#3898 Remove: duplicate page
  docs/developer-docs/getting-started/explore-examples.mdx
  docs/developer-docs/web-apps/application-frontends/default-frontend.mdx
  docs/developer-docs/web-apps/application-frontends/overview.mdx
  docs/tutorials/developer-journey/level-1/1.3-first-dapp.mdx
  plugins/utils/redirects.js
  sidebars.js
Labels: documentation

#3893 fix: example transfer app link
  docs/developer-docs/defi/tokens/token-standards.mdx
Labels: documentation

#3895 fix: word order
  docs/developer-docs/web-apps/application-frontends/existing-frontend.mdx
Labels: documentation

#3911 spec: improve canister status explanation
  docs/references/ic-interface-spec.md
Labels: interface-spec

#3900 Update: prerequisite format/content
  docs/developer-docs/ai/ai-on-chain.mdx
  docs/developer-docs/ai/machine-learning-sample.mdx
  docs/developer-docs/defi/cycles/cycles-wallet.mdx
  docs/developer-docs/defi/exchange-rate-canister.mdx
  docs/developer-docs/defi/nfts/nft-collections.mdx
  docs/developer-docs/defi/tokens/indexes.mdx
  docs/developer-docs/defi/wallets/self-custody/hardware-wallet-cli.mdx
  docs/developer-docs/defi/wallets/self-custody/self-custody-quickstart.mdx
  docs/developer-docs/developer-tools/cli-tools/idl2json.mdx
  docs/developer-docs/developer-tools/off-chain/canpack.mdx
  docs/developer-docs/getting-started/write-smart-contracts.mdx
  docs/developer-docs/identity/internet-identity/integrate-internet-identity.mdx
  docs/developer-docs/smart-contracts/encryption/using-vetkeys.mdx
  roadmap/roadmap.json
  sidebars.js
Labels: documentation

#3908 feat: textual description of ic0.msg_method_name_size and ic0.msg_method_name_copy
  docs/references/ic-interface-spec.md
Labels: interface-spec
