Repository dfinity/portal, pull requests merged in 2025-04, with the labels that each got.

#3764 feat: Best-effort responses
  docs/references/_attachments/interface-spec-changelog.md
  docs/references/ic-interface-spec.md
Labels: interface-spec

#5601 chore: note on ic0. prefix
  docs/references/ic-interface-spec.md
Labels: interface-spec

#5490 fix "twitter": "https://twitter.com/odoc_ic"
  showcase.json
Labels: external-contributor

#5471 Remove outdated item
  showcase.json
  static/img/showcase/cyclestransferstation_logo.png
Labels: external-contributor

#5552 update: interact w/ canisters tags
  docs/building-apps/interact-with-canisters/advanced-calls.mdx
  docs/building-apps/interact-with-canisters/candid/candid-tools.mdx
  docs/building-apps/interact-with-canisters/candid/using-candid.mdx
  docs/building-apps/interact-with-canisters/query-calls.mdx
  docs/building-apps/interact-with-canisters/update-calls.mdx
Labels: documentation

#5615 feat(icrc-rosetta): adapt ICRC Rosetta documentation to multitoken feature
  docs/defi/rosetta/icrc_rosetta/index.mdx
Labels: documentation

#5611 fix: missing comma
  docs/building-apps/frontends/existing-frontend.mdx
  plugins/utils/redirects.js
Labels: documentation

#5608 update: expand page on dfx.json configuration options
  docs/building-apps/developer-tools/dfx-json.mdx
Labels: documentation

#5612 fix: typo
  docs/building-apps/frontends/custom-domains/using-custom-domains.mdx
Labels: documentation

#5624 fix: misc links
  docs/tutorials/developer-liftoff/level-0/index.mdx
  docs/tutorials/developer-liftoff/level-1/1.3-intro-dfx.mdx
  docs/tutorials/developer-liftoff/level-1/1.4-using-cycles.mdx
  docs/tutorials/developer-liftoff/level-1/1.5-deploying-canisters.mdx
  docs/tutorials/developer-liftoff/level-1/1.6-managing-canisters.mdx
  docs/tutorials/developer-liftoff/level-2/2.2-advanced-canister-calls.mdx
  docs/tutorials/developer-liftoff/level-2/2.3-third-party-canisters.mdx
  docs/tutorials/developer-liftoff/level-2/2.4-intro-candid.mdx
  docs/tutorials/developer-liftoff/level-2/2.5-unit-testing.mdx
  docs/tutorials/developer-liftoff/level-3/3.4-intro-to-agents.mdx
  docs/tutorials/developer-liftoff/level-3/3.6-motoko-lvl3.mdx
  docs/tutorials/developer-liftoff/level-4/4.1-icp-ledger.mdx
  docs/tutorials/developer-liftoff/level-4/4.2-icrc-tokens.mdx
  docs/tutorials/developer-liftoff/level-4/4.3-ckbtc-and-bitcoin.mdx
  docs/tutorials/developer-liftoff/level-5/5.1-vetKeys-tutorial.mdx
  docs/tutorials/developer-liftoff/level-5/5.3-token-swap-tutorial.mdx
  docs/tutorials/developer-liftoff/level-5/5.4-NFT-tutorial.mdx
  docs/tutorials/developer-liftoff/level-5/5.5-auction-tutorial.mdx
  plugins/utils/redirects.js
Labels: documentation

#5614 Update sns-checklist.mdx
  docs/building-apps/governing-apps/tokenomics/sns-checklist.mdx
Labels: documentation

#5629 chore: remark on canister snapshots in Interface Specification
  docs/references/ic-interface-spec.md
Labels: interface-spec

#5627 fix(security): Fix broken hyperlinks
  docs/building-apps/security/canister-upgrades.mdx
  docs/building-apps/security/data-integrity-and-authenticity.mdx
  docs/building-apps/security/data-storage.mdx
  docs/building-apps/security/decentralization.mdx
  docs/building-apps/security/dos.mdx
  docs/building-apps/security/https-outcalls.mdx
  docs/building-apps/security/iam.mdx
  docs/building-apps/security/inter-canister-calls.mdx
  docs/building-apps/security/misc.mdx
  docs/building-apps/security/observability-and-monitoring.mdx
  docs/building-apps/security/resources.mdx
Labels: documentation

#5634 update: Dev best practices
  docs/building-apps/best-practices/application-architectures.mdx
  docs/building-apps/best-practices/general.mdx
  docs/building-apps/best-practices/idempotency.mdx
  docs/building-apps/best-practices/reproducible-builds.mdx
  docs/building-apps/best-practices/storage.mdx
  docs/defi/chain-key-tokens/ckbtc/using-ckbtc-in-dapps.mdx
  docs/defi/defi-best-practices.mdx
  sidebars.js
Labels: documentation

#5630 update: General troubleshooting page
  docs/building-apps/best-practices/troubleshooting.mdx
Labels: documentation

#5489 feat: Specify a hard lower limit for canister's freezing threshold
  docs/references/_attachments/interface-spec-changelog.md
  docs/references/ic-interface-spec.md
Labels: interface-spec

#5639 fix: init args
  docs/defi/create.mdx
  docs/defi/token-ledgers/setup/icrc1_ledger_setup.mdx
Labels: documentation

#5640 fix: more init args
  docs/building-apps/developer-tools/advanced-dfx/init-args.mdx
Labels: documentation

#5641 add: Info about ic-alloy
  docs/building-apps/chain-fusion/ethereum/evm-rpc/evm-rpc-canister.mdx
  docs/building-apps/chain-fusion/ethereum/evm-rpc/overview.mdx
  docs/building-apps/chain-fusion/ethereum/using-eth/eth-dev-workflow.mdx
Labels: documentation

#5642 add: Auth client info for external wallets
  docs/building-apps/authentication/integrate-internet-identity.mdx
  docs/building-apps/authentication/integrate-misc-wallets.mdx
  sidebars.js
Labels: documentation

#5643 fix: misc links
  docs/building-apps/governing-apps/nns/using-the-nns-dapp/nns-dapp-additional-features.mdx
  src/pages/ai-agents.tsx
Labels: documentation

#5656 fix: links with `//`
  docs/tutorials/developer-liftoff/level-4/4.3-ckbtc-and-bitcoin.mdx
  how-it-works/6_webaccess/01_web_access.subpage.md
  plugins/utils/redirects.js
  src/components/BitcoinIntegrationPage/Content/index.tsx
Labels: documentation

#5655 fix: import
  docs/tutorials/developer-liftoff/level-2/2.4-intro-candid.mdx
Labels: documentation

#5647 revise: ICP essentials category
  docs/building-apps/essentials/canisters.mdx
  docs/building-apps/essentials/cost-estimations-and-examples.mdx
  docs/building-apps/essentials/gas-cost.mdx
  docs/building-apps/essentials/message-execution.mdx
  docs/building-apps/essentials/network-overview.mdx
  docs/references/_attachments/transaction-overview.svg
  docs/references/cycles-cost-formulas.mdx
  plugins/utils/redirects.js
  sidebars.js
Labels: documentation

#5660 fix: typo
  blog/news-and-updates/2024-10-09-update.mdx
  docs/building-apps/essentials/gas-cost.mdx
  docs/building-apps/getting-started/tokens-and-cycles.mdx
  docs/tutorials/developer-liftoff/level-1/1.4-using-cycles.mdx
  src/pages/what-is-the-ic.tsx
Labels: documentation

#5662 revise: Token standard pages
  docs/defi/create.mdx
  docs/defi/nft-collections.mdx
  docs/defi/token-standards/index.mdx
Labels: documentation

#5653 update: local replica -> PocketIC + PocketIC page updates
  blog/features/evm-rpc-canister-launch.mdx
  blog/news-and-updates/2024-01-31-update.mdx
  blog/news-and-updates/2024-06-19-update.mdx
  blog/news-and-updates/2024-10-09-update.mdx
  docs/building-apps/advanced/test/pocket-ic.mdx
  docs/building-apps/authentication/integrate-internet-identity.mdx
  docs/building-apps/canister-management/cycles-wallet.mdx
  docs/building-apps/chain-fusion/bitcoin/using-btc/btc-dev-workflow.mdx
  docs/building-apps/chain-fusion/bitcoin/using-btc/create-transactions.mdx
  docs/building-apps/chain-fusion/bitcoin/using-btc/generate-addresses.mdx
  docs/building-apps/chain-fusion/bitcoin/using-btc/read-state.mdx
  docs/building-apps/chain-fusion/bitcoin/using-btc/sign-transactions.mdx
  docs/building-apps/chain-fusion/bitcoin/using-btc/submit-transactions.mdx
  docs/building-apps/chain-fusion/ethereum/evm-rpc/evm-rpc-canister.mdx
  docs/building-apps/developer-tools/cdks/rust/intercanister.mdx
  docs/building-apps/developer-tools/cdks/rust/intro-to-rust.mdx
  docs/building-apps/developer-tools/dev-tools-overview.mdx
  docs/building-apps/developer-tools/dfx-json.mdx
  docs/building-apps/developer-tools/dfx/dfx-deps.mdx
  docs/building-apps/developing-canisters/create.mdx
  docs/building-apps/developing-canisters/write.mdx
  docs/building-apps/getting-started/install.mdx
  docs/building-apps/getting-started/troubleshooting.mdx
  docs/building-apps/governing-apps/testing/testing-locally.mdx
  docs/building-apps/governing-apps/testing/testing-on-mainnet.mdx
  docs/building-apps/interact-with-canisters/agents/javascript-agent.mdx
  docs/building-apps/interact-with-canisters/agents/nodejs.mdx
  docs/building-apps/interact-with-canisters/query-calls.mdx
  docs/building-apps/interact-with-canisters/update-calls.mdx
  docs/building-apps/network-features/signatures/t-ecdsa.mdx
  docs/building-apps/network-features/signatures/t-schnorr.mdx
  docs/building-apps/security/resources.mdx
  docs/building-apps/test/overview.mdx
  docs/building-apps/test/pocket-ic.mdx
  docs/defi/nft-collections.mdx
  docs/defi/token-indexes/index.mdx
  docs/defi/token-ledgers/setup/icp_ledger_setup.mdx
  docs/references/bitcoin-how-it-works.mdx
  docs/references/https-outcalls-how-it-works.mdx
  docs/references/system-canisters/xrc.mdx
  docs/references/t-sigs-how-it-works.mdx
  docs/tutorials/developer-liftoff/level-1/1.2-dev-env.mdx
  docs/tutorials/developer-liftoff/level-1/1.3-intro-dfx.mdx
  docs/tutorials/developer-liftoff/level-1/1.4-using-cycles.mdx
  docs/tutorials/developer-liftoff/level-1/1.5-deploying-canisters.mdx
  docs/tutorials/developer-liftoff/level-1/index.mdx
  docs/tutorials/developer-liftoff/level-2/2.5-unit-testing.mdx
  docs/tutorials/developer-liftoff/level-3/3.4-intro-to-agents.mdx
  docs/tutorials/developer-liftoff/level-4/4.3-ckbtc-and-bitcoin.mdx
  docs/tutorials/developer-liftoff/level-4/4.5-using-quill.mdx
  docs/tutorials/developer-liftoff/level-5/5.1-vetKeys-tutorial.mdx
  plugins/utils/redirects.js
  roadmap/entries/deployed-dx.json
  roadmap/roadmap.json
  sidebars.js
Labels: documentation

#5664 revise: Developing canisters -> Write
  docs/building-apps/developing-canisters/write.mdx
Labels: documentation

#5665 revise: Developing canisters -> Compile
  docs/building-apps/developing-canisters/compile.mdx
Labels: documentation

#5663 remove: Duplicate content about canisters/canister lifecycle
  docs/building-apps/developing-canisters/create.mdx
  docs/building-apps/developing-canisters/deploy.mdx
  docs/building-apps/developing-canisters/install.mdx
  docs/building-apps/developing-canisters/what-are-canisters.mdx
  docs/building-apps/developing-canisters/write.mdx
  docs/building-apps/essentials/canisters.mdx
  docs/building-apps/interact-with-canisters/agents/nodejs.mdx
  docs/building-apps/interact-with-canisters/query-calls.mdx
  docs/references/execution-errors.mdx
  docusaurus.config.js
  plugins/utils/redirects.js
  sidebars.js
  src/pages/capabilities/actor-model.tsx
  src/pages/capabilities/limitless-scaling.tsx
  src/pages/capabilities/multi-chain-transactions.tsx
  src/pages/capabilities/serve-web-content.tsx
  src/pages/capabilities/sovereign-network.tsx
  src/pages/capabilities/web-speed.tsx
  what-is-the-ic/3_canisters/index.md
Labels: documentation

#5674 add: brew command
  docs/building-apps/getting-started/install.mdx
  docs/building-apps/getting-started/quickstart.mdx
Labels: documentation

#5661 revise: Ledger setup/usage docs + token standard page
  docs/defi/create.mdx
  docs/defi/nft-collections.mdx
  docs/defi/overview.mdx
  docs/defi/token-ledgers/setup/icp_ledger_setup.mdx
  docs/defi/token-ledgers/setup/icrc1_ledger_setup.mdx
  docs/defi/token-ledgers/usage/icp_ledger_usage.mdx
  docs/defi/token-ledgers/usage/icrc1_ledger_usage.mdx
  docs/defi/token-standards/index.mdx
Labels: documentation

#5667 revise: Developing canisters -> Deploy
  docs/building-apps/developer-tools/advanced-dfx/init-args.mdx
  docs/building-apps/developer-tools/advanced-dfx/networks-json.mdx
  docs/building-apps/developer-tools/advanced-dfx/specifying-replica-version.mdx
  docs/building-apps/developer-tools/dfx-json.mdx
  docs/building-apps/developing-canisters/custom-networks.mdx
  docs/building-apps/developing-canisters/deploy.mdx
  docs/defi/token-ledgers/setup/icp_ledger_setup.mdx
  plugins/utils/redirects.js
  sidebars.js
Labels: documentation

#5636 IwinPool Project Showcase
  showcase.json
  static/img/showcase/iwinpool_logo.webp
  static/img/showcase/iwinpool_screenshot.webp
Labels: external-contributor

#5682 fix: Fix broken links around cycles-cost-formula page
  docs/building-apps/essentials/gas-cost.mdx
  docs/references/https-outcalls-how-it-works.mdx
Labels: documentation

#5690 fix: improve stop canister specification
  docs/references/ic-interface-spec.md
Labels: interface-spec

#5680 revise: ckToken pages and ICP/ICRC index page
  docs/defi/chain-key-tokens/ckbtc/overview.mdx
  docs/defi/chain-key-tokens/ckbtc/using-ckbtc-in-dapps.mdx
  docs/defi/chain-key-tokens/ckerc20/creating-new-ckerc20.mdx
  docs/defi/chain-key-tokens/ckerc20/making-transactions.mdx
  docs/defi/chain-key-tokens/ckerc20/overview.mdx
  docs/defi/chain-key-tokens/ckerc20/using-ckerc20-in-dapps.mdx
  docs/defi/chain-key-tokens/cketh/overview.mdx
  docs/defi/chain-key-tokens/cketh/using-cketh-in-dapps.mdx
  docs/defi/chain-key-tokens/overview.mdx
  docs/defi/defi-best-practices.mdx
  docs/defi/token-indexes/index.mdx
  docs/defi/token-integrations/index.mdx
  docs/defi/token-ledgers/cycles-ledger.mdx
Labels: documentation

#5684 fix: Issue #5676
  docs/building-apps/canister-management/delete.mdx
  docs/tutorials/developer-liftoff/level-1/1.6-managing-canisters.mdx
Labels: documentation

#5693 fix: misc file paths
  blog/news-and-updates/2023-06-28-update.mdx
  blog/news-and-updates/2023-09-06-update.mdx
  blog/news-and-updates/2023-12-20-update.mdx
  blog/news-and-updates/2024-05-29-update.mdx
  docs/building-apps/developer-tools/cdks/rust/intercanister.mdx
  docs/tutorials/developer-liftoff/level-0/02-ic-terms.mdx
  docs/tutorials/developer-liftoff/level-1/1.1-motoko-lvl1.mdx
  docs/tutorials/developer-liftoff/level-1/1.5-deploying-canisters.mdx
Labels: documentation
