Repository dfinity/portal, pull requests merged in 2025-05, with the labels that each got.

#5700 Update Docs on `Application architecture`
  docs/building-apps/getting-started/app-architecture.mdx
Labels: external-contributor

#5696 fix: Dev Journey 4.3
  docs/tutorials/developer-liftoff/level-4/4.3-ckbtc-and-bitcoin.mdx
Labels: documentation

#5671 Create sns-topic-following.mdx
  docs/building-apps/governing-apps/_attachments/sns_topic_following_a_neuron_and_the_section_vote_delegation.png
  docs/building-apps/governing-apps/_attachments/sns_topic_following_delegate_voting_collapsed.png
  docs/building-apps/governing-apps/_attachments/sns_topic_following_delegate_voting_empty.png
  docs/building-apps/governing-apps/_attachments/sns_topic_following_delegate_voting_with_current_delegates.png
  docs/building-apps/governing-apps/_attachments/sns_topic_following_delegate_voting_with_no_ticks.png
  docs/building-apps/governing-apps/_attachments/sns_topic_following_enter_neuron_to_follow.png
  docs/building-apps/governing-apps/_attachments/sns_topic_following_how_to_get_to_neurons_table.png
  docs/building-apps/governing-apps/_attachments/sns_topic_following_shows_catch_all_applied.png
  docs/building-apps/governing-apps/_attachments/sns_topic_following_topic_definition_list.png
  docs/building-apps/governing-apps/_attachments/sns_topic_following_topic_with_underlying_choices.png
  docs/building-apps/governing-apps/nns/using-the-nns-dapp/nns-dapp-sns-topic-following.mdx
  sidebars.js
Labels: documentation

#5708 Update local-development.mdx
  docs/building-apps/chain-fusion/bitcoin/using-btc/local-development.mdx
Labels: documentation

#5709 update: query calls
  docs/building-apps/interact-with-canisters/query-calls.mdx
Labels: documentation

#5685 change image
  community/communityProjects.ts
  showcase.json
  static/img/showcase/MercX-logo-Cover-2-.jpg
Labels: external-contributor

#5713 fix: incorrect capitalization
  docs/building-apps/chain-fusion/bitcoin/using-btc/local-development.mdx
Labels: documentation

#5703 Remove experimental flag from Schnorr API
  docs/references/ic-interface-spec.md
Labels: interface-spec

#5694 chore: Remove experimental note for composite queries and canister logs
  docs/references/_attachments/interface-spec-changelog.md
  docs/references/ic-interface-spec.md
Labels: interface-spec

#5691 fix: clarify traps and other fixes
  docs/references/ic-interface-spec.md
Labels: interface-spec

#5686 FI-1648: Add documentation for upgrading ICRC-1 ledger suite canisters
  docs/defi/token-ledgers/upgrading/icrc1_ledger_upgrade.mdx
  sidebars.js
Labels: documentation

#5721 Update eth-comparison.mdx
  docs/building-apps/chain-fusion/ethereum/using-eth/eth-comparison.mdx
Labels: documentation

#5731 Revert "Update application-architectures.mdx"
  docs/building-apps/best-practices/application-architectures.mdx
Labels: documentation

#5740 chore: canister_logs => New_canister_logs
  docs/references/ic-interface-spec.md
Labels: interface-spec

#5711 fix: CSP details
  docs/building-apps/frontends/asset-security.mdx
Labels: documentation

#5716 revise: Rust docs
  docs/building-apps/developer-tools/cdks/rust/canister-state.mdx
  docs/building-apps/developer-tools/cdks/rust/generating-candid.mdx
  docs/building-apps/developer-tools/cdks/rust/intercanister.mdx
  docs/building-apps/developer-tools/cdks/rust/intro-to-rust.mdx
  docs/building-apps/developer-tools/cdks/rust/message-inspect.mdx
  docs/building-apps/developer-tools/cdks/rust/rust-limitations.mdx
  docs/building-apps/developer-tools/cdks/rust/stable-structures.mdx
  docs/building-apps/developer-tools/cdks/rust/upgrading.mdx
  sidebars.js
Labels: documentation

#5757 fix: candid-extractor link
  docs/building-apps/developer-tools/cdks/rust/generating-candid.mdx
Labels: documentation

#5764 Add ICPrize to showcase
  showcase.json
  static/img/showcase/favicon.png
Labels: external-contributor

#5776 chore: clarify state in canister lifecycle in Interface Specification
  docs/references/ic-interface-spec.md
Labels: interface-spec

#5766 doc: update Rust agent doc
  docs/building-apps/interact-with-canisters/agents/rust-agent.mdx
Labels: documentation

#5785 update: cycles cost table values
  docs/building-apps/essentials/gas-cost.mdx
  docs/building-apps/getting-started/tokens-and-cycles.mdx
  docs/references/bitcoin-how-it-works.mdx
  docs/references/cycles-cost-formulas.mdx
  docs/references/t-sigs-how-it-works.mdx
Labels: documentation

#5762 feat: non-ASCII characters allowed in canister http URL
  docs/references/_attachments/interface-spec-changelog.md
  docs/references/ic-interface-spec.md
Labels: interface-spec

#5784 fix: refine max canister http transformed response size
  docs/references/_attachments/interface-spec-changelog.md
  docs/references/ic-interface-spec.md
Labels: interface-spec
