Repository dfinity/portal, pull requests merged in 2025-02, with the labels that each got.

#4760 remove: cost reduction note
  docs/developer-docs/defi/exchange-rate-canister.mdx
Labels: documentation

#4886 fix: cycles_balance => cycle_balance
  docs/references/ic-interface-spec.md
Labels: interface-spec

#4885 docs(Ledger): FI-1598: Remove obsolete documentation on account trimming
  docs/developer-docs/defi/icp-tokens/account-trimming.mdx
  plugins/utils/redirects.js
  sidebars.js
Labels: documentation

#3930 Update II mobile integration sequence diagrams to use mermaid
  docs/developer-docs/security/security-best-practices/iam.mdx
Labels: documentation

#3827 fix: link to alternative origins
  docs/developer-docs/web-apps/custom-domains/using-custom-domains.mdx
Labels: documentation

#5023 Update glossary.mdx - Replica Definition
  docs/references/glossary.mdx
Labels: external-contributor

#4480 adding investafarm showcase
  roadmap/roadmap.json
  showcase.json
  static/img/showcase/Investafarm_logo.png
Labels: external-contributor

#3790 feat: new System API ic0.subnet_self
  docs/references/_attachments/interface-spec-changelog.md
  docs/references/ic-interface-spec.md
Labels: interface-spec

#4392 update: Runes Indexer API
  docs/developer-docs/multi-chain/bitcoin/using-btc/runes.mdx
Labels: documentation

#5244 Adjust freezing threshold wording
  docs/developer-docs/smart-contracts/maintain/settings.mdx
Labels: documentation

#3927 Update sns.subpage.md
  how-it-works/3_governance/sns.subpage.md
Labels: external-contributor

#5242 Example and tutorial for creating a DeAI coding assistant on ICP
  docs/developer-docs/ai/inference.mdx
  docs/developer-docs/ai/overview.mdx
Labels: external-contributor

#5432 Update 1.3-first-dapp.mdx - npm install not needed
  docs/tutorials/developer-liftoff/level-1/1.3-first-dapp.mdx
Labels: external-contributor

#5435 Update 1.3-first-dapp.mdx - Remove line about external CSS
  docs/tutorials/developer-liftoff/level-1/1.3-first-dapp.mdx
Labels: external-contributor

#5438 Update 2.2-advanced-canister-calls.mdx - Add link to ingress messages
  docs/tutorials/developer-liftoff/level-2/2.2-advanced-canister-calls.mdx
Labels: external-contributor

#5185 docs(EXC-1744): Document canister backtraces
  .github/CODEOWNERS
  docs/developer-docs/smart-contracts/maintain/backtraces.mdx
  sidebars.js
Labels: documentation

#5430 Update 1.3-first-dapp.mdx
  docs/tutorials/developer-liftoff/level-1/1.3-first-dapp.mdx
Labels: external-contributor

#5436 Update 2.1-storage-persistence.mdx - Remove Rust stable memory workflow
  docs/tutorials/developer-liftoff/level-2/2.1-storage-persistence.mdx
Labels: external-contributor

#5447 Update 3.2-https-outcalls.mdx - Fix typo
  docs/tutorials/developer-liftoff/level-3/3.2-https-outcalls.mdx
Labels: external-contributor

#5458 docs(ICRC_Ledger): FI-1666: Elaborate on ledger archiving options
  docs/developer-docs/defi/tokens/create.mdx
Labels: documentation

#5444 docs(EXC): Add ic-wasm version to backtrace docs
  docs/developer-docs/smart-contracts/maintain/backtraces.mdx
Labels: documentation

#5465 chore: Remove warning that Bitcoin testnet canister is disabled & fix links
  docs/developer-docs/multi-chain/bitcoin/using-btc/btc-dev-workflow.mdx
  docs/developer-docs/multi-chain/bitcoin/using-btc/local-development.mdx
Labels: documentation

#5462 Update 10-resources.mdx - Fix link to the Awesome Computer Repo
  docs/tutorials/hackathon-prep-course/10-resources.mdx
Labels: external-contributor

#5464 Update dfx-json.mdx - Add short type description for assets and pullable
  docs/developer-docs/developer-tools/cli-tools/dfx-json.mdx
Labels: external-contributor

#5456 update: vetKeys docs
  blog/features/vetkey-primer.md
  docs/developer-docs/smart-contracts/encryption/using-vetkeys.mdx
  docs/developer-docs/smart-contracts/encryption/vetkeys.mdx
  docs/references/vetkeys-overview.mdx
  plugins/utils/redirects.js
  static/.ic-assets.json
Labels: documentation

#5467 fix: dfx.json incomplete sentence
  docs/developer-docs/developer-tools/cli-tools/dfx-json.mdx
Labels: documentation

#3881 Tidy up inter-canister calls
  docs/references/ic-interface-spec.md
Labels: interface-spec

#3865 Add docs best effort responses
  docs/developer-docs/backend/rust/counter.mdx
  docs/developer-docs/backend/rust/intercanister.mdx
  docs/developer-docs/defi/tokens/ledger/usage/icp_ledger_usage.mdx
  docs/developer-docs/defi/tokens/ledger/usage/icrc1_ledger_usage.mdx
  docs/developer-docs/security/security-best-practices/inter-canister-calls.mdx
  docs/developer-docs/smart-contracts/advanced-features/async-code.mdx
  docs/developer-docs/smart-contracts/best-practices/idempotency.mdx
  docs/developer-docs/smart-contracts/call/overview.mdx
  docs/references/message-execution-properties.mdx
Labels: documentation

#5483 fix: bullet point indentation
  docs/building-apps/developing-canisters/create.mdx
Labels: documentation
