Repository dfinity/portal, pull requests merged in 2025-03, with the labels that each got.

#5468 Removing unmaintained ic agents
  docs/building-apps/interact-with-canisters/agents/overview.mdx
  docs/tutorials/developer-liftoff/level-3/3.4-intro-to-agents.mdx
Labels: documentation

#5484 Update local-development.mdx
  docs/building-apps/chain-fusion/_attachments/bitcoin-local-send-tx.png
  docs/building-apps/chain-fusion/bitcoin/using-btc/local-development.mdx
Labels: documentation

#5499 remove: ICP Ninja Chain Fusion limitation
  docs/building-apps/developer-tools/icp-ninja.mdx
Labels: documentation

#5500 update: proposal cost
  docs/building-apps/governing-apps/nns/concepts/proposals/proposal-overview.mdx
  docs/building-apps/governing-apps/nns/proposal-submit.mdx
Labels: documentation

#5510 fix: Make tags consistent
  docs/building-apps/developing-canisters/create.mdx
  docs/building-apps/developing-canisters/deploy.mdx
  docs/building-apps/developing-canisters/what-are-canisters.mdx
  docs/building-apps/developing-canisters/write.mdx
Labels: documentation

#5186 adding fries coin to showcase
  showcase.json
  static/img/showcase/friescoin_logo.jpg
Labels: external-contributor

#5470 fix(spec): Clarify the remark on reject codes
  docs/references/ic-interface-spec.md
Labels: interface-spec

#3987 Add ICExplorer to showcase
  community/communityProjects.ts
  showcase.json
  static/img/showcase/ic-explorer_logo.png
  static/img/showcase/ic-explorer_screenshot.jpg
Labels: external-contributor

#3761 feat: on low wasm memory hook
  docs/references/_attachments/ic.did
  docs/references/_attachments/interface-spec-changelog.md
  docs/references/ic-interface-spec.md
Labels: interface-spec

#5527 add: subaccount definition
  docs/defi/token-standards/index.mdx
Labels: documentation

#5240 Add memory_metrics to canister_status.
  docs/references/_attachments/ic.did
  docs/references/_attachments/interface-spec-changelog.md
  docs/references/ic-interface-spec.md
Labels: external-contributor, interface-spec

#5525 remove: BTC terms
  docs/building-apps/chain-fusion/bitcoin/using-btc/btc-comparison.mdx
Labels: documentation

#4888 add BeProActive to ICP ecosystem showcase
  showcase.json
  static/img/showcase/beproactive_logo.webp
  static/img/showcase/beproactive_screenshot.webp
Labels: external-contributor

#5522 add: moc version for latest dfx version
  MOTOKO_MAINTENANCE.md
  README.md
  docs/building-apps/getting-started/install.mdx
Labels: documentation

#5524 add: Info about --enable-bitcoin flag or dfx.json config options
  docs/building-apps/chain-fusion/bitcoin/using-btc/btc-dev-workflow.mdx
  docs/building-apps/chain-fusion/bitcoin/using-btc/create-transactions.mdx
  docs/building-apps/chain-fusion/bitcoin/using-btc/generate-addresses.mdx
  docs/building-apps/chain-fusion/bitcoin/using-btc/read-state.mdx
  docs/building-apps/chain-fusion/bitcoin/using-btc/sign-transactions.mdx
  docs/building-apps/chain-fusion/bitcoin/using-btc/submit-transactions.mdx
Labels: documentation

#5530 remove: Rustic
  docs/building-apps/developer-tools/cdks/rust/intro-to-rust.mdx
Labels: documentation

#5532 fix: heading size + update call sync/async
  docs/building-apps/essentials/message-execution.mdx
  docs/building-apps/interact-with-canisters/update-calls.mdx
Labels: documentation

#5539 docs(tutorials): remove accidental repetitions
  docs/tutorials/hackathon-prep-course/3-exploring-the-backend.mdx
Labels: cla:agreed, external-contributor

#5550 update: Canister creation fee 100B -> 500B
  docs/defi/token-ledgers/cycles-ledger.mdx
Labels: documentation

#5551 fix: Dev tool tags
  docs/building-apps/developer-tools/dev-tools-overview.mdx
  docs/building-apps/developer-tools/icp-ninja.mdx
Labels: documentation

#5549 Update provider url for project-specific networks in dfx
  docs/building-apps/developer-tools/advanced-dfx/networks-json.mdx
Labels: external-contributor

#3756 feat: specify ic0.canister_liquid_cycle_balance128
  docs/references/_attachments/interface-spec-changelog.md
  docs/references/ic-interface-spec.md
Labels: interface-spec

#5512 feat: specify that a canister can have multiple snapshots
  docs/references/_attachments/interface-spec-changelog.md
  docs/references/ic-interface-spec.md
Labels: interface-spec

#5564 chore(ICRC_Ledger): Add quotes to search string in ICRC ledger suite release link
  docs/defi/token-ledgers/setup/icrc1_ledger_setup.mdx
Labels: documentation

#5565 Improve Https outcalls cost documentation
  docs/building-apps/essentials/gas-cost.mdx
  docs/references/https-outcalls-how-it-works.mdx
Labels: documentation

#5575 Remove NNS dev docs and redirect to Learn Hub pages
  blog/features/node-metrics.md
  blog/news-and-updates/2023-06-28-update.mdx
  blog/news-and-updates/2023-09-13-update.mdx
  docs/building-apps/best-practices/trust-in-canisters.mdx
  docs/building-apps/canister-management/cycles-wallet.mdx
  docs/building-apps/chain-fusion/ethereum/using-eth/eth-comparison.mdx
  docs/building-apps/developing-canisters/what-are-canisters.mdx
  docs/building-apps/developing-canisters/write.mdx
  docs/building-apps/governing-apps/managing/managing-nervous-system-parameters.mdx
  docs/building-apps/governing-apps/nns/becoming-a-known-neuron.mdx
  docs/building-apps/governing-apps/nns/concepts/neurons-fund.mdx
  docs/building-apps/governing-apps/nns/concepts/neurons/becoming-a-known-neuron.mdx
  docs/building-apps/governing-apps/nns/concepts/neurons/neuron-following.mdx
  docs/building-apps/governing-apps/nns/concepts/neurons/neuron-management.mdx
  docs/building-apps/governing-apps/nns/concepts/neurons/neuron-overview.mdx
  docs/building-apps/governing-apps/nns/concepts/neurons/staking-voting-rewards.mdx
  docs/building-apps/governing-apps/nns/concepts/proposals/direct-voting.mdx
  docs/building-apps/governing-apps/nns/concepts/proposals/proposal-overview.mdx
  docs/building-apps/governing-apps/nns/concepts/proposals/proposal-topics.mdx
  docs/building-apps/governing-apps/nns/concepts/proposals/verify-proposals.mdx
  docs/building-apps/governing-apps/nns/direct-voting.mdx
  docs/building-apps/governing-apps/nns/neuron-following.mdx
  docs/building-apps/governing-apps/nns/neuron-management.mdx
  docs/building-apps/governing-apps/nns/neuron-overview.mdx
  docs/building-apps/governing-apps/nns/overview.mdx
  docs/building-apps/governing-apps/nns/proposal-overview.mdx
  docs/building-apps/governing-apps/nns/proposal-submit.mdx
  docs/building-apps/governing-apps/nns/proposal-topics.mdx
  docs/building-apps/governing-apps/nns/staking-voting-rewards.mdx
  docs/building-apps/governing-apps/nns/using-the-nns-dapp/nns-dapp-advanced-neuron-operations.mdx
  docs/building-apps/governing-apps/nns/using-the-nns-dapp/nns-dapp-following-other-neurons.mdx
  docs/building-apps/governing-apps/nns/using-the-nns-dapp/nns-dapp-making-neurons-public.mdx
  docs/building-apps/governing-apps/nns/using-the-nns-dapp/nns-dapp-voting-on-proposals.mdx
  docs/building-apps/governing-apps/nns/verify-proposals.mdx
  docs/building-apps/governing-apps/overview.mdx
  docs/building-apps/governing-apps/tokenomics/rewards.mdx
  docs/building-apps/governing-apps/tokenomics/tokenomics-intro.mdx
  docs/building-apps/security/decentralization.mdx
  docs/defi/chain-key-tokens/overview.mdx
  docs/references/system-canisters/index.mdx
  docs/tutorials/developer-liftoff/level-4/4.4-nns-governance.mdx
  plugins/utils/redirects.js
  roadmap/entries/deployed-governance.json
  sidebars.js
  src/pages/sns.tsx
  src/pages/sns/faq.tsx
Labels: documentation

#5568 fix: upload asset sentence
  docs/building-apps/frontends/uploading-serving-assets.mdx
Labels: documentation

#5587 Update showcase.json
  showcase.json
Labels: external-contributor

#5578 chore: update aws instructions
  docs/building-apps/frontends/custom-domains/dns-setup.mdx
  docs/building-apps/frontends/custom-domains/route53-subdomain.png
Labels: documentation

#5513 add bookie to showcase
  showcase.json
  static/img/showcase/bookie_logo.webp
  static/img/showcase/bookie_screenshot.webp
Labels: external-contributor

#5593 chore: Add best practices regarding ckBTC
  docs/defi/chain-key-tokens/ckbtc/using-ckbtc-in-dapps.mdx
Labels: documentation

#5576 chore: Cleaning up the Bitcoin integration and ckBTC documentation
  docs/building-apps/chain-fusion/bitcoin/overview.mdx
  docs/building-apps/chain-fusion/bitcoin/using-btc/create-transactions.mdx
  docs/building-apps/chain-fusion/bitcoin/using-btc/read-state.mdx
  docs/building-apps/chain-fusion/ethereum/overview.mdx
  docs/references/bitcoin-how-it-works.mdx
  docs/references/ckbtc-reference.mdx
  src/components/BitcoinIntegrationPage/Content/index.tsx
  src/components/BitcoinIntegrationPage/Hero/index.tsx
  src/components/BitcoinIntegrationPage/HowItWorks/index.tsx
  src/pages/bitcoin-integration.tsx
Labels: documentation

#5594 fix: relative links
  docs/building-apps/governing-apps/index.mdx
  docs/building-apps/governing-apps/launching/launch-summary-1proposal.mdx
  docs/building-apps/governing-apps/managing/making-proposals.mdx
  docs/building-apps/governing-apps/nns/concepts/neurons/becoming-a-known-neuron.mdx
  docs/building-apps/governing-apps/tokenomics/index.mdx
  docs/building-apps/governing-apps/tokenomics/preparation.mdx
  docs/building-apps/governing-apps/tokenomics/sns-checklist.mdx
  plugins/utils/redirects.js
  roadmap/roadmap.json
Labels: documentation
