Repository dfinity/portal, pull requests merged in 2025-07, with the labels that each got.

#5897 add: CRP-2871 Motoko code to vetKeys IBE
  docs/building-apps/network-features/vetkeys/identity-based-encryption.mdx
Labels: documentation

#5905 chore: CRP-2694 remove the link to the deleted encrypted notes dapp
  docs/building-apps/security/resources.mdx
Labels: documentation

#5856 Adding ic-deploy-actions on developer tools section
  src/components/Common/toolingItems.ts
Labels: external-contributor

#5908 chore: Format
  docs/references/_attachments/ic.did
Labels: interface-spec

#5885 feat(rosetta): Add Python scripts to Rosetta's documentation
  docs/defi/rosetta/icp_rosetta/examples.mdx
  docs/defi/rosetta/icrc_rosetta/examples.mdx
  sidebars.js
Labels: external-contributor, documentation

#5928 chore: CRP-2864 CRP-2867 improve vetKeys api page
  docs/building-apps/network-features/vetkeys/_attachments/vetkd_diagram.png
  docs/building-apps/network-features/vetkeys/api.mdx
Labels: documentation

#5939 Add IPv4 support documentation
  docs/references/https-outcalls-how-it-works.mdx
  docs/references/ic-interface-spec.md
  docs/tutorials/developer-liftoff/level-3/3.2-https-outcalls.mdx
Labels: interface-spec, documentation

#5807 Rust Developer Liftoff Level 1
  docs/tutorials/developer-liftoff-rust/level-1/1.1-rust-lvl1.mdx
  docs/tutorials/developer-liftoff-rust/level-1/1.2-rust-dev-env.mdx
  docs/tutorials/developer-liftoff-rust/level-1/1.3-intro-dfx.mdx
  docs/tutorials/developer-liftoff-rust/level-1/1.4-using-cycles.mdx
  docs/tutorials/developer-liftoff-rust/level-1/1.5-deploying-canisters.mdx
  docs/tutorials/developer-liftoff-rust/level-1/1.6-managing-canisters.mdx
  docs/tutorials/developer-liftoff/level-1/1.5-deploying-canisters.mdx
Labels: documentation

#5959 chore: CRP-2868 CRP-2875 pass input as parameter in vetKD API
  docs/building-apps/network-features/vetkeys/api.mdx
Labels: documentation

#5957 chore: added page about canister access logs
  .github/CODEOWNERS
  docs/building-apps/advanced/canister-access-logs.mdx
  sidebars.js
Labels: documentation

#5966 Update resource-limits.mdx
  docs/building-apps/canister-management/resource-limits.mdx
Labels: documentation

#5860 fix: corrected a typo in stable-structures.mdx
  docs/building-apps/developer-tools/cdks/rust/stable-structures.mdx
Labels: external-contributor

#5803 Rust Developer Liftoff: Levels 0-2
  docs/building-apps/best-practices/application-architectures.mdx
  docs/tutorials/developer-liftoff-rust/index.mdx
  docs/tutorials/developer-liftoff-rust/level-0/01-ic-overview.mdx
  docs/tutorials/developer-liftoff-rust/level-0/02-ic-terms.mdx
  docs/tutorials/developer-liftoff-rust/level-0/03-intro-canisters.mdx
  docs/tutorials/developer-liftoff-rust/level-0/04-intro-languages.mdx
  docs/tutorials/developer-liftoff-rust/level-0/05-tooling.mdx
  docs/tutorials/developer-liftoff-rust/level-0/06-first-dapp.mdx
  docs/tutorials/developer-liftoff-rust/level-0/index.mdx
  docs/tutorials/developer-liftoff-rust/level-1/1.1-rust-lvl1.mdx
  docs/tutorials/developer-liftoff-rust/level-1/1.2-rust-dev-env.mdx
  docs/tutorials/developer-liftoff-rust/level-1/1.3-intro-dfx.mdx
  docs/tutorials/developer-liftoff-rust/level-1/1.4-using-cycles.mdx
  docs/tutorials/developer-liftoff-rust/level-1/1.5-deploying-canisters.mdx
  docs/tutorials/developer-liftoff-rust/level-1/1.6-managing-canisters.mdx
  docs/tutorials/developer-liftoff-rust/level-2/2.1-canister-calls.mdx
  docs/tutorials/developer-liftoff-rust/level-2/2.2-storage-memory.mdx
  docs/tutorials/developer-liftoff-rust/level-2/2.3-canister-state.mdx
  docs/tutorials/developer-liftoff-rust/level-2/2.4-stable-memory.mdx
  docs/tutorials/developer-liftoff-rust/level-2/2.5-upgrading-rust.mdx
  docs/tutorials/developer-liftoff-rust/level-2/2.6-rust-lvl2.mdx
  docs/tutorials/developer-liftoff/index.mdx
  docs/tutorials/developer-liftoff/level-0/06-first-dapp.mdx
  docs/tutorials/developer-liftoff/level-1/1.5-deploying-canisters.mdx
  docs/tutorials/developer-liftoff/level-2/2.1-storage-persistence.mdx
  docs/tutorials/developer-liftoff/level-3/3.5-identities-and-auth.mdx
  docs/tutorials/developer-liftoff/level-5/5.2-ICP-ETH-tutorial.mdx
  docs/tutorials/hackathon-prep-course/1-hello-world.mdx
  docs/tutorials/hackathon-prep-course/2-static-website.mdx
  docs/tutorials/hackathon-prep-course/3-first-fullstack-dapp.mdx
  docs/tutorials/hackathon-prep-course/4-evm-block-explorer.mdx
  docs/tutorials/hackathon-prep-course/5-create-deploy-token.mdx
  sidebars.js
Labels: documentation

#5974 chore: update Ninja limitations
  docs/building-apps/developer-tools/icp-ninja.mdx
Labels: documentation

#5972 docs: Rust Dev Liftoff Level 3
  docs/tutorials/developer-liftoff-rust/_attachments/II-int-1.png
  docs/tutorials/developer-liftoff-rust/_attachments/II-int-2.png
  docs/tutorials/developer-liftoff-rust/_attachments/II-int-3.png
  docs/tutorials/developer-liftoff-rust/_attachments/II_1.png
  docs/tutorials/developer-liftoff-rust/_attachments/II_2.png
  docs/tutorials/developer-liftoff-rust/_attachments/II_3.png
  docs/tutorials/developer-liftoff-rust/_attachments/II_4.png
  docs/tutorials/developer-liftoff-rust/_attachments/II_5.png
  docs/tutorials/developer-liftoff-rust/_attachments/II_6.png
  docs/tutorials/developer-liftoff-rust/_attachments/II_7.png
  docs/tutorials/developer-liftoff-rust/level-3/3.1-testing-rust.mdx
  docs/tutorials/developer-liftoff-rust/level-3/3.2-logging-history.mdx
  docs/tutorials/developer-liftoff-rust/level-3/3.3-canister-snapshots.mdx
  docs/tutorials/developer-liftoff-rust/level-3/3.4-identity-auth.mdx
  docs/tutorials/developer-liftoff-rust/level-3/3.5-access-control.mdx
  docs/tutorials/developer-liftoff-rust/level-3/3.6-rust-lvl3.mdx
  docs/tutorials/developer-liftoff/index.mdx
  sidebars.js
Labels: documentation

#5977 Update the Rust inter-canister calls tutorial to new CDK version
  docs/building-apps/developer-tools/cdks/rust/intercanister.mdx
Labels: documentation

#5978 fix Rust time fetching syntax
  docs/building-apps/network-features/time-and-timestamps.mdx
Labels: documentation

#5980 chore: rm references to to-be-deleted examples
  docs/building-apps/interact-with-canisters/query-calls.mdx
  docs/building-apps/interact-with-canisters/update-calls.mdx
  docs/tutorials/developer-liftoff-rust/level-2/2.1-canister-calls.mdx
  docs/tutorials/developer-liftoff/level-2/2.6-motoko-lvl2.mdx
  docs/tutorials/developer-liftoff/level-3/3.4-intro-to-agents.mdx
Labels: documentation

#5955 Update testing-before-launch.mdx
  docs/building-apps/governing-apps/index.mdx
  docs/building-apps/governing-apps/testing/testing-before-launch.mdx
  docs/building-apps/governing-apps/testing/testing-locally.mdx
  docs/building-apps/governing-apps/tokenomics/sns-checklist.mdx
  docs/tutorials/developer-liftoff/level-4/4.4-nns-governance.mdx
  sidebars.js
Labels: documentation

#5962 Update making-proposals.mdx
  docs/building-apps/governing-apps/managing/making-proposals.mdx
Labels: documentation
