Repository dfinity/portal, pull requests merged in 2025-01, with the labels that each got.

#3914 Added reference to the global R&D talk on II mobile integration.
  docs/developer-docs/security/security-best-practices/iam.mdx
Labels: documentation

#3918 Update import.mdx with the correct link.
  docs/developer-docs/smart-contracts/maintain/import.mdx
Labels: documentation

#3916 update: asset certification info
  docs/developer-docs/web-apps/application-frontends/asset-security.mdx
  docs/developer-docs/web-apps/application-frontends/overview.mdx
Labels: documentation

#3922 Rewrite Internet Identity integration documentation.
  docs/developer-docs/identity/internet-identity/integrate-internet-identity.mdx
Labels: documentation

#3925 Update overview.mdx
  docs/developer-docs/daos/sns/overview.mdx
Labels: external-contributor

#3917 Add note about an issue in SNS testflight
  docs/developer-docs/daos/sns/testing/testing-on-mainnet.mdx
  search/Cargo.lock
Labels: documentation

#3926 clarify: create canister with cycles commands
  docs/developer-docs/defi/cycles/cycles-ledger.mdx
Labels: documentation

#3913 Update bridge23
  showcase.json
  static/img/showcase/bridge23_logo.svg
Labels: external-contributor

#3939 Update neuron-management.mdx
  docs/developer-docs/daos/nns/concepts/neurons/neuron-management.mdx
Labels: documentation

#3934 fix: remove hidden characters from Custom Domains commands
  docs/developer-docs/web-apps/custom-domains/using-custom-domains.mdx
Labels: documentation

#3758 feat(crypto): Add support for Schnorr auxiliary inputs
  docs/references/_attachments/ic.did
  docs/references/_attachments/interface-spec-changelog.md
  docs/references/ic-interface-spec.md
Labels: interface-spec

#3944 fix reference to point to the correct CDK
  docs/developer-docs/getting-started/write-smart-contracts.mdx
Labels: documentation

#3938 Contribute showcase: OfficeX
  showcase.json
  static/img/showcase/officex_logo.webp
  static/img/showcase/officex_screenshot.webp
Labels: external-contributor

#3956 Added documentation for periodic confirmation in the NNS dapp
  docs/developer-docs/daos/_attachments/periodic-1.webp
  docs/developer-docs/daos/_attachments/periodic-2.webp
  docs/developer-docs/daos/_attachments/periodic-3.webp
  docs/developer-docs/daos/_attachments/periodic-4.webp
  docs/developer-docs/daos/_attachments/periodic-5.webp
  docs/developer-docs/daos/nns/using-the-nns-dapp/nns-dapp-confirm-following.mdx
  sidebars.js
Labels: documentation

#3955 Update inter-canister-calls.mdx to reference message execution proper…
  docs/developer-docs/security/security-best-practices/inter-canister-calls.mdx
Labels: documentation

#3952 update: remove Bitfinity EVM early development note
  docs/developer-docs/backend/solidity/index.mdx
  docs/developer-docs/developer-tools/on-chain/cdks.mdx
Labels: documentation

#3951 add: latest ic-asset certification doc
  docs/developer-docs/web-apps/http-compatible-canisters/03-serving-static-assets-ic-assets.md
  docs/developer-docs/web-apps/http-compatible-canisters/04-serving-static-assets-over-http.md
  sidebars.js
Labels: documentation

#3957 fix: style and grammar of new NNS docs page
  docs/developer-docs/daos/nns/using-the-nns-dapp/nns-dapp-confirm-following.mdx
Labels: documentation

#3947 docs(ICRC_Ledger): FI-1621: Add docs on changing ledger token metadata
  docs/developer-docs/defi/tokens/create.mdx
Labels: documentation

#3949 add BIP341 to threshold Schnorr docs
  docs/developer-docs/smart-contracts/signatures/signing-messages-t-schnorr.mdx
  docs/references/t-sigs-how-it-works.mdx
Labels: documentation

#3948 add BIP341 key tweaking to bitcoin examples
  docs/developer-docs/multi-chain/bitcoin/using-btc/generate-addresses.mdx
  docs/developer-docs/multi-chain/bitcoin/using-btc/sign-transactions.mdx
Labels: documentation

#3969 [SPEC] unify management canister method anchors format
  docs/references/ic-interface-spec.md
Labels: interface-spec

#3760 [FINAL] feat: Allow accepting and burning cycles in replicated queries
  docs/references/_attachments/interface-spec-changelog.md
  docs/references/ic-interface-spec.md
Labels: interface-spec

#3959 Update 02_consensus.subpage.md
  how-it-works/1_protocol/02_consensus.subpage.md
Labels: external-contributor

#3986 update: ICP Ninja docs
  docs/developer-docs/developer-tools/ide/icp-ninja.mdx
  docs/developer-docs/getting-started/explore-examples.mdx
  docs/developer-docs/getting-started/write-smart-contracts.mdx
  docs/developer-docs/multi-chain/ethereum/evm-rpc/how-it-works.mdx
  docs/developer-docs/smart-contracts/development-workflow.mdx
  plugins/utils/redirects.js
  sidebars.js
  src/components/Card/index.tsx
Labels: documentation

#3954 Update react-quickstart.mdx to include the libunwind prerequisite for Debian/Ubuntu
  docs/developer-docs/web-apps/application-frontends/quickstart/react-quickstart.mdx
Labels: external-contributor

#3932 Update NetworkStats.tsx
  src/components/DocsHome/NetworkStats.tsx
Labels: external-contributor

#3978 revise: Trust in canisters page
  docs/developer-docs/smart-contracts/overview/trust-in-canisters.mdx
Labels: documentation

#4363 add: Neuron pagination
  docs/developer-docs/daos/nns/concepts/neurons/neuron-management.mdx
Labels: documentation
